[package]
name = "detours-macro"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["proc-macro"]

[dependencies]
regex = "1.5.4"
proc-macro2 = "1.0.36"
quote = "1.0.15"
lazy_static = "1.4.0"

[dependencies.syn]
version = "1.0.86"
features = ["full"]